In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [20]:
##Sentences

sent = [ 'the glass of milk',
    'the glass of juice',
    'the cup fo tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',]

In [21]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup fo tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [22]:
##Define the vocabulary size
voc_size = 10000

In [23]:
##One hot representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]

one_hot_repr

[[640, 4289, 4271, 4084],
 [640, 4289, 4271, 2005],
 [640, 5485, 8391, 3278],
 [7486, 5332, 6833, 285, 7227],
 [7486, 5332, 6833, 285, 5593],
 [7930, 640, 5568, 4271, 4705],
 [5956, 3158, 462, 285]]

In [24]:
#Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [25]:
sent_length = 8

embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length) ##Pre will add zeors on the start of sentences

print(embedded_docs)

[[   0    0    0    0  640 4289 4271 4084]
 [   0    0    0    0  640 4289 4271 2005]
 [   0    0    0    0  640 5485 8391 3278]
 [   0    0    0 7486 5332 6833  285 7227]
 [   0    0    0 7486 5332 6833  285 5593]
 [   0    0    0 7930  640 5568 4271 4705]
 [   0    0    0    0 5956 3158  462  285]]


In [26]:
##Feature representation
dim=10

In [28]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [49]:
pred = model.predict(embedded_docs)

pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[[-0.02824236,  0.02677516,  0.03387615, -0.02940536,
         -0.04354317, -0.0354787 , -0.00704335,  0.01274568,
          0.01638745,  0.00011506],
        [-0.02824236,  0.02677516,  0.03387615, -0.02940536,
         -0.04354317, -0.0354787 , -0.00704335,  0.01274568,
          0.01638745,  0.00011506],
        [-0.02824236,  0.02677516,  0.03387615, -0.02940536,
         -0.04354317, -0.0354787 , -0.00704335,  0.01274568,
          0.01638745,  0.00011506],
        [-0.02824236,  0.02677516,  0.03387615, -0.02940536,
         -0.04354317, -0.0354787 , -0.00704335,  0.01274568,
          0.01638745,  0.00011506],
        [ 0.03172532,  0.0255002 ,  0.00096994, -0.00241736,
          0.0060286 , -0.0186054 , -0.01289313,  0.02253732,
         -0.00809272,  0.01610963],
        [-0.0057724 , -0.01966033, -0.04517125,  0.02321334,
         -0.02999516, -0.0095862 ,  0.03954687,  0.02186232,
          0.02802298,  0.04174428],
        [ 0.02192327,  0.01373372, -0.002178  , -0.0

In [50]:
pred[0]

array([[-0.02824236,  0.02677516,  0.03387615, -0.02940536, -0.04354317,
        -0.0354787 , -0.00704335,  0.01274568,  0.01638745,  0.00011506],
       [-0.02824236,  0.02677516,  0.03387615, -0.02940536, -0.04354317,
        -0.0354787 , -0.00704335,  0.01274568,  0.01638745,  0.00011506],
       [-0.02824236,  0.02677516,  0.03387615, -0.02940536, -0.04354317,
        -0.0354787 , -0.00704335,  0.01274568,  0.01638745,  0.00011506],
       [-0.02824236,  0.02677516,  0.03387615, -0.02940536, -0.04354317,
        -0.0354787 , -0.00704335,  0.01274568,  0.01638745,  0.00011506],
       [ 0.03172532,  0.0255002 ,  0.00096994, -0.00241736,  0.0060286 ,
        -0.0186054 , -0.01289313,  0.02253732, -0.00809272,  0.01610963],
       [-0.0057724 , -0.01966033, -0.04517125,  0.02321334, -0.02999516,
        -0.0095862 ,  0.03954687,  0.02186232,  0.02802298,  0.04174428],
       [ 0.02192327,  0.01373372, -0.002178  , -0.02831929,  0.02303418,
        -0.01360831, -0.00628027,  0.02747374